version: '2'

services:
  benchmark-nginx:
    image: nginx:1.17-alpine
    container_name: benchmark-nginx
    networks:
      - benchmark
    volumes:
      - .:/code:cached
    ports:
      - "80:80"
    env_file:
      - .env
    command: /code/build/container/nginx/run.sh
    depends_on:
      - benchmark-fpm
    logging:
      driver: none

  benchmark-fpm:
    build: ./
    container_name: benchmark-fpm
    networks:
      - benchmark
    env_file:
      - .env
    command: /code/build/container/fpm/run.sh
    logging:
      driver: none

networks:
  benchmark:
